using UnityEngine;
using UnityEngine.UI;
using Spine.Unity;
using System.Collections.Generic;

/// <summary>
/// Loads two Spine models from Resources and places them in the scene,
/// with the camera positioned to view both models.
/// Includes UI buttons to show/hide individual models.
/// </summary>
public class SpineModelSetup : MonoBehaviour
{
    [Header("Camera Settings")]
    public Camera mainCamera;
    
    [Header("Model 1 - NIKKE Makima (2948057129)")]
    public string skeletonPath1 = "2948057129/NIKKE Makima/skeleton_0";
    public string atlasPath1 = "2948057129/NIKKE Makima/atlases_0_atlas_0";
    public Vector3 position1 = new Vector3(-3f, 0f, 0f);
    public float scale1 = 0.01f;
    
    [Header("Model 2 - NIKKE Makima (3111154553)")]
    public string skeletonPath2 = "3111154553/[NIKKE] Makima/skeleton_0";
    public string atlasPath2 = "3111154553/[NIKKE] Makima/atlases_0_atlas_0";
    public Vector3 position2 = new Vector3(3f, 0f, 0f);
    public float scale2 = 0.01f;
    
    [Header("Camera Configuration")]
    public float cameraDistance = 12f;
    public float cameraHeight = 4f;
    public float cameraFOV = 50f;
    public float cameraLookAtY = 3f;
    
    [Header("UI Settings")]
    public float buttonWidth = 150f;
    public float buttonHeight = 50f;
    public float buttonSpacing = 10f;
    public Color buttonNormalColor = Color.white;
    public Color buttonActiveColor = new Color(0.3f, 0.8f, 0.3f);
    
    private List<GameObject> spawnedModels = new List<GameObject>();
    private Canvas uiCanvas;
    private Button[] modelButtons;
    
    void Start()
    {
        if (mainCamera == null)
        {
            mainCamera = Camera.main;
        }
        
        SetupCamera();
        SpawnModels();
        CreateUI();
    }
    
    void SetupCamera()
    {
        if (mainCamera != null)
        {
            mainCamera.transform.position = new Vector3(0f, cameraHeight, -cameraDistance);
            mainCamera.transform.LookAt(new Vector3(0f, cameraLookAtY, 0f));
            mainCamera.fieldOfView = cameraFOV;
            mainCamera.clearFlags = CameraClearFlags.SolidColor;
            mainCamera.backgroundColor = new Color(0.15f, 0.15f, 0.18f, 1f);
            Debug.Log($"Camera set up at {mainCamera.transform.position}");
        }
    }
    
    void SpawnModels()
    {
        // Try loading pre-imported SkeletonDataAsset first (generated by Spine Unity Editor)
        SkeletonDataAsset sda1 = Resources.Load<SkeletonDataAsset>(skeletonPath1 + "_SkeletonData");
        if (sda1 == null)
        {
            // Fallback: create from JSON + atlas
            sda1 = CreateSkeletonDataAsset(skeletonPath1, atlasPath1, scale1);
        }
        
        if (sda1 != null)
        {
            GameObject m1 = CreateSpineGameObject(sda1, "Model_NIKKE_Makima_1", position1, scale1);
            if (m1 != null)
                spawnedModels.Add(m1);
        }
        else
        {
            Debug.LogError($"[SpineModelSetup] Failed to load model 1 from: {skeletonPath1}");
        }
        
        // Model 2
        SkeletonDataAsset sda2 = Resources.Load<SkeletonDataAsset>(skeletonPath2 + "_SkeletonData");
        if (sda2 == null)
        {
            sda2 = CreateSkeletonDataAsset(skeletonPath2, atlasPath2, scale2);
        }
        
        if (sda2 != null)
        {
            GameObject m2 = CreateSpineGameObject(sda2, "Model_NIKKE_Makima_2", position2, scale2);
            if (m2 != null)
                spawnedModels.Add(m2);
        }
        else
        {
            Debug.LogError($"[SpineModelSetup] Failed to load model 2 from: {skeletonPath2}");
        }
        
        Debug.Log($"[SpineModelSetup] Spawned {spawnedModels.Count} model(s)");
    }
    
    SkeletonDataAsset CreateSkeletonDataAsset(string skeletonPath, string atlasPath, float scale)
    {
        // Load skeleton JSON/SKEL from Resources
        TextAsset skeletonTextAsset = Resources.Load<TextAsset>(skeletonPath);
        if (skeletonTextAsset == null)
        {
            Debug.LogError($"[SpineModelSetup] Cannot load skeleton: {skeletonPath}");
            return null;
        }
        
        // Load atlas asset
        SpineAtlasAsset atlasAsset = Resources.Load<SpineAtlasAsset>(atlasPath);
        if (atlasAsset == null)
        {
            Debug.LogError($"[SpineModelSetup] Cannot load atlas: {atlasPath}");
            return null;
        }
        
        // Create SkeletonDataAsset
        SkeletonDataAsset sda = ScriptableObject.CreateInstance<SkeletonDataAsset>();
        sda.skeletonJSON = skeletonTextAsset;
        sda.atlasAssets = new SpineAtlasAsset[] { atlasAsset };
        sda.scale = scale;
        
        // Pre-load to validate
        Spine.SkeletonData skelData = sda.GetSkeletonData(false);
        if (skelData == null)
        {
            Debug.LogError($"[SpineModelSetup] Failed to parse skeleton data from: {skeletonPath}");
            return null;
        }
        
        Debug.Log($"[SpineModelSetup] Loaded skeleton: {skelData.Name}, " +
                  $"animations: {skelData.Animations.Count}, " +
                  $"skins: {skelData.Skins.Count}");
        
        return sda;
    }
    
    GameObject CreateSpineGameObject(SkeletonDataAsset skeletonDataAsset, string name, Vector3 position, float scale)
    {
        GameObject go = new GameObject(name);
        go.transform.position = position;
        go.transform.localScale = Vector3.one;
        
        // Add SkeletonAnimation (this automatically adds MeshFilter + MeshRenderer)
        SkeletonAnimation skeletonAnimation = SkeletonAnimation.AddToGameObject(go, skeletonDataAsset);
        
        if (skeletonAnimation == null)
        {
            Debug.LogError($"[SpineModelSetup] Failed to create SkeletonAnimation for: {name}");
            Destroy(go);
            return null;
        }
        
        // Set skin to default
        skeletonAnimation.Skeleton.SetSkin(skeletonAnimation.Skeleton.Data.DefaultSkin);
        skeletonAnimation.Skeleton.SetSlotsToSetupPose();
        
        // Play idle animation if available, otherwise first animation
        Spine.SkeletonData skelData = skeletonDataAsset.GetSkeletonData(false);
        if (skelData != null && skelData.Animations.Count > 0)
        {
            Spine.Animation idleAnim = skelData.FindAnimation("idle");
            if (idleAnim == null)
            {
                // Try "standby" or other common names
                idleAnim = skelData.FindAnimation("standby");
            }
            if (idleAnim == null)
            {
                idleAnim = skelData.FindAnimation("default");
            }
            if (idleAnim == null)
            {
                // Use first animation
                idleAnim = skelData.Animations.Items[0];
            }
            
            skeletonAnimation.AnimationState.SetAnimation(0, idleAnim, true);
            Debug.Log($"[SpineModelSetup] Playing animation: {idleAnim.Name} on {name}");
        }
        
        skeletonAnimation.Skeleton.UpdateWorldTransform();
        
        Debug.Log($"[SpineModelSetup] Created {name} at {position}");
        return go;
    }
    
    void CreateUI()
    {
        // Create Canvas
        GameObject canvasObj = new GameObject("ModelSelectionCanvas");
        uiCanvas = canvasObj.AddComponent<Canvas>();
        uiCanvas.renderMode = RenderMode.ScreenSpaceOverlay;
        uiCanvas.sortingOrder = 100;
        
        CanvasScaler scaler = canvasObj.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);
        
        canvasObj.AddComponent<GraphicRaycaster>();
        
        // Create vertical layout for buttons
        GameObject buttonContainer = new GameObject("ButtonContainer");
        buttonContainer.transform.SetParent(canvasObj.transform);
        
        RectTransform containerRect = buttonContainer.AddComponent<RectTransform>();
        containerRect.anchorMin = new Vector2(0, 1);
        containerRect.anchorMax = new Vector2(0, 1);
        containerRect.pivot = new Vector2(0, 1);
        containerRect.anchoredPosition = new Vector2(20, -20);
        containerRect.sizeDelta = new Vector2(buttonWidth + 40, (buttonHeight + buttonSpacing) * (spawnedModels.Count + 1));
        
        VerticalLayoutGroup layout = buttonContainer.AddComponent<VerticalLayoutGroup>();
        layout.spacing = buttonSpacing;
        layout.childAlignment = TextAnchor.UpperLeft;
        layout.childForceExpandWidth = false;
        layout.childForceExpandHeight = false;
        
        // Create buttons
        modelButtons = new Button[spawnedModels.Count + 1];
        
        // "Show All" button
        modelButtons[0] = CreateButton(buttonContainer.transform, "Show All", 0, buttonActiveColor);
        
        // Individual model buttons
        for (int i = 0; i < spawnedModels.Count; i++)
        {
            string modelName = spawnedModels[i].name;
            modelButtons[i + 1] = CreateButton(buttonContainer.transform, modelName, i + 1, buttonNormalColor);
        }
        
        Debug.Log($"[SpineModelSetup] UI created with {modelButtons.Length} buttons");
    }
    
    Button CreateButton(Transform parent, string label, int modelIndex, Color color)
    {
        // Create button GameObject
        GameObject buttonObj = new GameObject($"Button_{label}");
        buttonObj.transform.SetParent(parent, false);
        
        RectTransform rectTransform = buttonObj.AddComponent<RectTransform>();
        rectTransform.sizeDelta = new Vector2(buttonWidth, buttonHeight);
        
        // Add Image component
        Image image = buttonObj.AddComponent<Image>();
        image.color = color;
        
        // Add Button component
        Button button = buttonObj.AddComponent<Button>();
        ColorBlock colors = button.colors;
        colors.highlightedColor = new Color(color.r * 0.9f, color.g * 0.9f, color.b * 0.9f);
        colors.pressedColor = new Color(color.r * 0.7f, color.g * 0.7f, color.b * 0.7f);
        button.colors = colors;
        
        // Add text
        GameObject textObj = new GameObject("Text");
        textObj.transform.SetParent(buttonObj.transform, false);
        
        RectTransform textRect = textObj.AddComponent<RectTransform>();
        textRect.anchorMin = Vector2.zero;
        textRect.anchorMax = Vector2.one;
        textRect.offsetMin = Vector2.zero;
        textRect.offsetMax = Vector2.zero;
        
        Text text = textObj.AddComponent<Text>();
        text.text = label;
        text.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        text.fontSize = 16;
        text.alignment = TextAnchor.MiddleCenter;
        text.color = Color.black;
        
        // Add click listener
        int index = modelIndex;
        button.onClick.AddListener(() => OnModelButtonClick(index));
        
        return button;
    }
    
    void OnModelButtonClick(int modelIndex)
    {
        if (modelIndex == 0)
        {
            // "Show All" - show all models
            foreach (var model in spawnedModels)
            {
                if (model != null)
                {
                    model.SetActive(true);
                }
            }
            UpdateButtonColors(-1); // -1 means all active
            Debug.Log("[SpineModelSetup] Showing all models");
        }
        else
        {
            // Show only the selected model
            int arrayIndex = modelIndex - 1;
            for (int i = 0; i < spawnedModels.Count; i++)
            {
                if (spawnedModels[i] != null)
                {
                    spawnedModels[i].SetActive(i == arrayIndex);
                }
            }
            UpdateButtonColors(modelIndex);
            Debug.Log($"[SpineModelSetup] Showing model: {spawnedModels[arrayIndex].name}");
        }
    }
    
    void UpdateButtonColors(int activeButtonIndex)
    {
        for (int i = 0; i < modelButtons.Length; i++)
        {
            Image buttonImage = modelButtons[i].GetComponent<Image>();
            if (buttonImage != null)
            {
                // Highlight "Show All" button (index 0) when activeButtonIndex is -1
                // Highlight individual model button when its index matches
                if (i == 0 && activeButtonIndex == -1)
                {
                    buttonImage.color = buttonActiveColor;
                }
                else if (i > 0 && i == activeButtonIndex)
                {
                    buttonImage.color = buttonActiveColor;
                }
                else
                {
                    buttonImage.color = buttonNormalColor;
                }
            }
        }
    }
    
    void Update()
    {
        // Press Space to rotate models
        if (Input.GetKeyDown(KeyCode.Space))
        {
            foreach (var model in spawnedModels)
            {
                if (model != null && model.activeSelf)
                {
                    model.transform.Rotate(0, 45f, 0);
                }
            }
        }
        
        // Press R to reset rotation
        if (Input.GetKeyDown(KeyCode.R))
        {
            foreach (var model in spawnedModels)
            {
                if (model != null)
                {
                    model.transform.rotation = Quaternion.identity;
                }
            }
        }
        
        // Press 1, 2, etc. to select models
        if (Input.GetKeyDown(KeyCode.Alpha1) && modelButtons.Length > 1)
        {
            OnModelButtonClick(1);
        }
        if (Input.GetKeyDown(KeyCode.Alpha2) && modelButtons.Length > 2)
        {
            OnModelButtonClick(2);
        }
        if (Input.GetKeyDown(KeyCode.Alpha0) || Input.GetKeyDown(KeyCode.A))
        {
            OnModelButtonClick(0);
        }
    }
}
